"""add title and thumbnail to recipe

Revision ID: 4c0693ef2a48
Revises: f1ebaa918faf
Create Date: 2025-09-06 16:44:27.554492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0693ef2a48'
down_revision: Union[str, Sequence[str], None] = 'f1ebaa918faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'thumbnail_url')
    op.add_column('recipes', sa.Column('title', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.drop_column('recipes', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'thumbnail_url')
    op.drop_column('recipes', 'title')
    op.add_column('dishes', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
