"""Refine Dish model for search optimization

Revision ID: f1ebaa918faf
Revises: 174b3419f99e
Create Date: 2025-09-03 16:40:58.755456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ebaa918faf'
down_revision: Union[str, Sequence[str], None] = '174b3419f99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('semantic_description', sa.Text(), nullable=True))
    op.add_column('dishes', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.drop_column('dishes', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('dishes', 'thumbnail_url')
    op.drop_column('dishes', 'semantic_description')
    # ### end Alembic commands ###
